version: '2.1'

services:
  mariadb:
    image: oa/mariadb:latest
    ports:
      - '3306:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    network_mode: "host"
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    volumes:
      - ../data:/bitnami/mariadb
