# Generated by Django 4.1.5 on 2023-02-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('london_cycle_map_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikePointCapacity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('in_use', models.IntegerField()),
            ],
        ),
    ]
