# Generated by Django 4.1.5 on 2023-02-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('london_cycle_map_app', '0002_bikepointcapacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikepointcapacity',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
