# Generated by Django 4.1.5 on 2023-02-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('london_cycle_map_app', '0003_bikepointcapacity_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikepointcapacity',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
